@HostAddressRoot = http://localhost:7167

GET {{HostAddressRoot}}/api/destinations?searchFor=San
Accept: application/json

###
GET {{HostAddressRoot}}/api/destinations?searchFor=Antwerp,%20Belgium
Accept: application/json

###
GET {{HostAddressRoot}}/api/destinations
Accept: application/json

###
PUT {{HostAddressRoot}}/api/destinations/1/images
Accept: application/json
Content-Type: application/json

 { 
   "ImagesToUpdate": [ 
    {
      "Name": "antwerp.jpg",
      "ImageBytes": "base64string"
    }, 
    {
      "Name": "antwerp2.jpg",
      "ImageBytes": "base64string"
    }, 
    {
      "Name": "sanfrancisco.jpg",
      "ImageBytes": "base64string"
    }]
 }

###
GET {{HostAddressRoot}}/api/processdestinationimagechanges
Accept: application/json 

###
GET {{HostAddressRoot}}/api/itineraries?searchFor=Paris
Accept: application/json

###
GET {{HostAddressRoot}}/api/itineraries/1/stops
Accept: application/json 
 

###
GET https://appdevstdevwetravel5.table.core.windows.net/Destinations?sp=r&st=2025-08-21T18:01:35Z&se=2025-08-22T18:01:00Z&spr=https&sv=2024-11-04&sig=zArwZzVbHqJ2jV3%2B5WTHIZYt7YsnZnlM84z792vle5M%3D&tn=Destinations
Accept: application/json

###
GET https://appdevstdevwetravel5.table.core.windows.net/Destinations?$filter=(Identifier%20ge%202)&sp=r&st=2025-08-21T18:01:35Z&se=2025-08-22T18:01:00Z&spr=https&sv=2024-11-04&sig=zArwZzVbHqJ2jV3%2B5WTHIZYt7YsnZnlM84z792vle5M%3D&tn=Destinations
Accept: application/json

###
GET https://appdevstdevwetravel5.table.core.windows.net/Destinations?$filter=(Identifier%20ge%202)&select=Identifier,Name&sp=r&st=2025-08-21T18:01:35Z&se=2025-08-22T18:01:00Z&spr=https&sv=2024-11-04&sig=zArwZzVbHqJ2jV3%2B5WTHIZYt7YsnZnlM84z792vle5M%3D&tn=Destinations
Accept: application/json